services:
  vein-finder:
    image: vecna-vein-finder
    container_name: vecna-vein-finder

    environment:
      DISPLAY: ${DISPLAY}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

    devices:
      - /dev/video0:/dev/video0

    stdin_open: true
    tty: true

    restart: "no"
